(function(){'use strict';
const API='https://nursing-learning-companion.drlatham.chatgpt.site',KEY='nursing-community-receipts-v1',$=id=>document.getElementById(id);let drafts=[],current=0,receipts=[];
try{receipts=JSON.parse(localStorage.getItem(KEY)||'[]')}catch{}if(!Array.isArray(receipts))receipts=[];
const say=(id,message)=>{$(id).textContent=message;};
async function api(path,method='GET',body,token){const r=await fetch(API+path,{method,headers:{...(body?{'Content-Type':'application/json'}:{}),...(token?{Authorization:'Bearer '+token}:{})},body:body?JSON.stringify(body):undefined});let data;try{data=await r.json()}catch{throw Error('Community service is unavailable. Your draft is still here.')}if(!r.ok)throw Error(data.error||'Could not complete the request.');return data;}
function values(){return {stem:$('q-question').value,options:$('q-options').value.split('\n').map(s=>s.trim()).filter(Boolean),answer:$('q-answer').value,rationale:$('q-rationale').value,topic:$('q-topic').value,track:$('q-track').value,author:$('q-author').value,sources:$('q-sources').value.split('\n').filter(s=>s.trim()).map(s=>{const i=s.indexOf('|');return {title:s.slice(0,i).trim(),url:s.slice(i+1).trim()}})};}
function fill(q){$('q-question').value=q.stem;$('q-options').value=q.options.join('\n');$('q-answer').value=Array.isArray(q.answer)?q.answer.map(i=>String.fromCharCode(65+i)).join(','):q.answer;$('q-rationale').value=q.rationale;$('q-topic').value=q.topic;$('q-track').value=q.track;$('q-author').value=q.author||'';$('q-sources').value=q.sources.map(s=>s.title+' | '+s.url).join('\n');for(const id of ['q-credit','q-rights','q-private','q-consent'])$(id).checked=false;}
function select(){const s=$('draft-select');s.replaceChildren();drafts.forEach((q,i)=>{const o=document.createElement('option');o.value=i;o.textContent=(i+1)+'. '+q.stem.slice(0,80);s.append(o)});s.hidden=$('draft-label').hidden=drafts.length<2;s.value=current;}
$('question-file').onchange=async()=>{try{const f=$('question-file').files[0];if(!f)return;if(f.size>100000)throw Error('Keep files under 100 KB.');drafts=NursingImport.parse(await f.text(),f.name);current=0;select();fill(drafts[0]);say('import-message',drafts.length+' question(s) loaded on this device. Review and submit each one below.')}catch(e){say('import-message',e.message)}};
$('draft-select').onchange=()=>{drafts[current]=values();current=Number($('draft-select').value);fill(drafts[current]);};
function save(){try{localStorage.setItem(KEY,JSON.stringify(receipts));return true}catch{say('receipt-status','This browser cannot save receipts. Download them now to retain access.');return false}}
function download(name,data){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function render(){const box=$('my-submissions');box.replaceChildren();if(!receipts.length){box.textContent='No submissions saved here yet.';return}for(const entry of receipts){const card=document.createElement('div');card.className='contribution';const title=document.createElement('strong');title.textContent=entry.title||'Your question';const state=document.createElement('p');state.textContent='Status: '+(entry.state||'pending');card.append(title,state);for(const [label,method] of [['Check status','GET'],['Withdraw','DELETE']]){const b=document.createElement('button');b.type='button';b.className='link-btn';b.textContent=label;b.disabled=entry.state==='withdrawn';b.onclick=async()=>{if(method==='DELETE'&&!confirm('Withdraw this question and remove its content from the community bank?'))return;b.disabled=true;try{const d=await api('/api/submissions/'+entry.id,method,undefined,entry.receipt);entry.state=d.state;save();render()}catch(e){state.textContent=e.message;b.disabled=false}};card.append(b)}box.append(card)}}
$('question-form').onsubmit=async e=>{e.preventDefault();const b=$('send-question');b.disabled=true;try{const q=NursingImport.normalize(values());Object.assign(q,{credit:$('q-credit').checked,rights:$('q-rights').checked,noPatientData:$('q-private').checked,reviewConsent:$('q-consent').checked});const d=await api('/api/submissions','POST',q);receipts.push({id:d.id,receipt:d.receipt,state:d.state,title:q.stem.slice(0,100)});save();render();say('submit-status','Received privately for review. It will only appear publicly after approval. Keep your receipt below.');drafts.splice(current,1);current=0;select();$('question-form').reset();if(drafts.length)fill(drafts[0]);}catch(e){say('submit-status',e.message)}finally{b.disabled=false}};
$('export-receipts').onclick=()=>download('nursing-private-receipts.json',receipts);
$('receipt-file').onchange=async()=>{try{const f=$('receipt-file').files[0];if(!f)return;if(f.size>100000)throw Error('Receipt file is too large.');const arr=JSON.parse(await f.text());if(!Array.isArray(arr)||arr.length>200||arr.some(r=>!r||!/^[-a-f0-9]{36}$/.test(r.id)||!/^[-a-f0-9]{64}$/.test(r.receipt)))throw Error('Invalid receipt file.');for(const r of arr)if(!receipts.some(x=>x.id===r.id))receipts.push({id:r.id,receipt:r.receipt,state:'unknown',title:typeof r.title==='string'?r.title.slice(0,100):'Restored question'});save();render();say('receipt-status','Receipts restored. Use Check status for current information.')}catch(e){say('receipt-status',e.message)}};render();
})();
