(function(){'use strict';
 const $=id=>document.getElementById(id),el=(tag,text)=>{const n=document.createElement(tag);if(text)n.textContent=text;return n;};let manifest,catalog,media,expansion,notes={};
 function key(){return 'nursing-review-notes-'+manifest.contentHash;}
 function save(){try{localStorage.setItem(key(),JSON.stringify(notes));$('review-save-state').textContent='Notes saved on this browser only.';}catch(_){$('review-save-state').textContent='Local storage unavailable. Export your notes before closing this page.';}}
 function download(data,name){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=el('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 function fields(id,host){const row=notes.items[id]||{};const label=el('label','Review decision'),select=el('select');[['not-reviewed','Not reviewed'],['changes-requested','Changes requested'],['recommended','Recommend approval after owner verification']].forEach(([v,t])=>{const o=el('option',t);o.value=v;select.append(o);});select.value=row.decision||'not-reviewed';label.append(select);host.append(label);
 const checks={};[['accuracy','Clinical accuracy and source support'],['mediaFidelity','Sample fidelity / question and answer fidelity'],['normalAbnormalDistinction','Expected versus abnormal distinctions / distractor quality'],['nursingImplications','Nursing implications and appropriate scope']].forEach(([id,text])=>{const label=el('label');label.className='check-line';const input=el('input');input.type='checkbox';input.checked=!!row.checks?.[id];checks[id]=input;label.append(input,el('span',text));host.append(label);});
 const nl=el('label','Findings, source concerns and requested corrections'),ta=el('textarea');ta.value=row.notes||'';ta.maxLength=10000;nl.append(ta);host.append(nl);
 function update(){notes.items[id]={decision:select.value,checks:Object.fromEntries(Object.entries(checks).map(([k,v])=>[k,v.checked])),notes:ta.value};save();}select.onchange=update;ta.oninput=update;Object.values(checks).forEach(input=>input.onchange=update);}
 Promise.all(['review-manifest.json','assessment/catalog.json','assessment/media-sources.json','expansion.json'].map(url=>fetch(url,{cache:'no-store'}).then(r=>{if(!r.ok)throw Error(url);return r.json();}))).then(([m,c,a,e])=>{manifest=m;catalog=c;media=a;expansion=e;
 try{notes=JSON.parse(localStorage.getItem(key())||'{}');}catch(_){}if(!notes||typeof notes!=='object'||Array.isArray(notes))notes={};notes.items=notes.items||{};
 $('review-total').textContent=c.lessons.length;$('review-drafts').textContent=e.packs.reduce((n,p)=>n+p.questions.length,0);$('review-hash').textContent=m.contentHash;$('review-code').value=notes.reviewerReference||'';$('review-code').oninput=()=>{notes.reviewerReference=$('review-code').value;save();};
 c.tutorials.forEach(t=>{const d=el('details');d.className='card review-item';d.id=t.id;d.append(el('summary',t.group+' · Required introduction'));t.paragraphs.forEach(p=>d.append(el('p',p)));t.questions.forEach(q=>{d.append(el('h3',q.stem));q.options.forEach((o,i)=>d.append(el('p',(i===q.answer?'✓ ':'')+o)));d.append(el('p',q.rationale));});fields(t.id,d);$('review-list').append(d);});
 c.lessons.forEach(l=>{const d=el('details');d.className='card review-item';d.id=l.id;d.append(el('summary',l.group+' · '+l.title));const a=el('a','Open comparison and source media ↗');a.href='assessment.html#'+l.id;a.target='_blank';a.rel='noopener noreferrer';d.append(a,el('p',l.context));fields(l.id,d);$('review-list').append(d);});
 (window.NURSING_PACKS||[]).forEach(p=>{const d=el('details');d.className='card review-item';d.append(el('summary',p.title),el('p',p.objectives.join(' · ')),el('p',p.lesson),el('p','Example: '+p.example),el('p','Common mistake: '+p.pitfall));fields('summary-'+p.id,d);$('summary-reviews').append(d);});
 e.packs.forEach(p=>{const d=el('details');d.className='review-item';d.append(el('summary',p.title+' · '+p.questions.length+' draft questions'));p.questions.forEach(q=>{const item=el('details');item.className='card review-item';item.append(el('summary',q.id+' · '+q.stem));q.options.forEach((o,i)=>item.append(el('p',(i===q.answer[0]?'✓ ':'')+o)));item.append(el('p',q.rationale));q.distractorExplanations.forEach(x=>item.append(el('p',x)));const source=el('a','Source');source.href=q.source;source.target='_blank';source.rel='noopener noreferrer';item.append(source);fields(q.id,item);d.append(item);});$('expansion-list').append(d);});
 $('export-review').onclick=()=>download({schemaVersion:1,contentHash:m.contentHash,exportedAt:new Date().toISOString(),...notes,notice:'Review recommendations only. Training and identity require owner verification. This file cannot unlock release.'},'nursing-review-notes-'+m.contentHash.slice(0,12)+'.json');
 $('download-review-package').onclick=()=>download({manifest:m,catalog:c,media:a,expansion:e,topicPacks:window.NURSING_PACKS},'nursing-review-inventory-'+m.contentHash.slice(0,12)+'.json');
 $('clear-review').onclick=()=>{if(confirm('Clear review notes stored in this browser for this version? Export first if you need to keep them.')){localStorage.removeItem(key());location.reload();}};
 if(location.hash){const target=$(decodeURIComponent(location.hash.slice(1)));if(target){target.open=true;target.scrollIntoView();}}
 }).catch(()=>{$('review-error').hidden=false;$('review-error').textContent='Review data could not load. Reconnect and reload. External release remains blocked.';['export-review','download-review-package','clear-review'].forEach(id=>$(id).disabled=true);});
})();
